### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by yuzhiyou1990** [Warchant/sr25519-crust#26]
Some errors occurred on the iOS system.

Undefined symbols for architecture x86_64:
  "_readdir$INODE64", referenced from:
      _macho_try_dsym in libsr25519crust.a(macho.o)
      _macho_add in libsr25519crust.a(macho.o)
  "_opendir$INODE64", referenced from:
      std::sys::unix::fs::readdir::h714714ee58a81923 in libsr25519crust.a(std-f5ac182b2a26610e.std.6cj6x2el-cgu.0.rcgu.o)
      _macho_try_dsym in libsr25519crust.a(macho.o)
      _macho_add in libsr25519crust.a(macho.o)
  "_readdir_r$INODE64", referenced from:
      _$LT$std..sys..unix..fs..ReadDir$u20$as$u20$core..iter..traits..iterator..Iterator$GT$::next::h3275646fa836ad24 in libsr25519crust.a(std-f5ac182b2a26610e.std.6cj6x2el-cgu.0.rcgu.o)
ld: symbol(s) not found for architecture x86_64

**Comment by Warchant** [comment]
Describe steps what you're doing

**Comment by yuzhiyou1990** [comment]
After cmake processing successfully, use libsr25519crust.a in iOS project

**Comment by burdges** [comment]
I suspect getrandom needs OS symbols for file access, so make sure you're using it correctly.  You could control it by including it yourself since cargo features are additive.
