### ISSUE TITLE
Add enum for verify result (as in schnorrkel 0.2.0)

### ISSUE THREAD

**Issue by Warchant** [Warchant/sr25519-crust#6]
Recently schnorrkel has been updated to 0.2.0: https://github.com/Warchant/sr25519-crust/pull/5

They changed return type of `sr25519_verify` function.
Previously it returned true/false, but now it returns result on enum.

The task is to update schnorrkel to 0.2.0, change return type of `sr25519_verify` from bool to enum (prefixed), with all possible errors:
```
enum sr25519_verify_outcome {
  sr25519_success = 0,
  ...
  (and other errors as non-0 codes)
}
```

**Comment by Warchant** [comment]
Closing for now #7

**Comment by burdges** [comment]
There is an argument in https://github.com/libp2p/rust-libp2p/pull/1127#discussion_r284405360 and ed25519-dalek that consistency reduces bugs, although I neglected to explain this in https://github.com/w3f/schnorrkel/commit/424ac1fda25c20ddbf9b890610b57ce635045504
